### PR TITLE
New kawoosh

### PR DESCRIPTION
**Pull request by dreson00**
- replaced old kawoosh effect with new model from blender
- texture sucks and will be replaced in the future
- fixed new event horizon shaders

### CODE REVIEW

**Comment by RafaelDeJongh** [comment]
How are you handling the kawoosh as a model exactly?

**Comment by LukePavelka** [comment]
> How are you handling the kawoosh as a model exactly?

blender exported a model with morph value that can move deformations in models.
we can then touch this value in the s&box code.

we chose this solution because we could not export from blender a model with animation that has animation based on deformation / morph. 

have I answered the question? (if not, please try to be specific about what you mean)

**Comment by dreson00** [comment]
https://www.youtube.com/watch?v=zXr3IFsYWiI&t=1287s&ab_channel=YottyLaboratories

We used this tutorial to get the model and exported it with accessible Shape key data that can be modified in game. It is possible to export it with the whole animation I think but I don't know how. 

This is the documentation for this.
https://wiki.facepunch.com/sbox/Importing_Morphs_and_Shape_Key_Animations

Currently, the animation is done by editing the Shape key morph value in _for_ cycles with GameTask.DelaySeconds(...) but it looks weird and laggy when the game (or perhaps the server, idk) has performance issues and I guess it's not really a good way to make animations. Katka suggested it might be better to use Event.Frame to make the animation smoother and generally better so I'm gonna try that.

Also the model has small holes in it so I'm gonna have to make it smoother and perhaps combine it with the particle kawoosh effect to make it look better.

**Comment by RafaelDeJongh** [comment]
Thanks for the detailed information, when we (main CAP developerd) tried to handle the many attempts to go for an animated model for the kawoosh we never really got what we wanted out of it, as you probably are experiencing some similarities to what we underwent. Although there are some new features included with later engine updates to make mesh animation/deformations more possible, the model approach never looked to feel right when we brought it in game.

Yet with a whole lot of new shades and an update lightning engine, I do think approaching it now with more realistic water shaders could potentially provide a more to the real deal kawoosh than what we ever could make back when we redid the whole gate model, textures, and system for GMOD.

So I'm honestly glad to hear you're taking this approach and well I am sure it will look a whole lot better than what we had to work with coming from simple smoke in the original Avon's Stargate edition, to optimise that and introduce some actual more glossy/wet looking smoke particles.

But yea if there is one thing I certainly would love to see changed would be the all the stargate assets, as in the right size for the Stargate, more accurate model and textures, actual naquadah or at least metal looking shaders, proper DHD's, and a properly consistent high quality event horizon animation. 

A new event horizon approach would be great if this was also an extention to the kawoosh being that it could form from the same morphing/animated model, to create the more water like ripple effect and to avoid big animated textures that tend to look way off due to compression as the higher quality looped texture has to be compromised with compression to not overflow the graphics buffer and make it too laggy for online play.

So if you ever have it near finished, I'd honestly would love to see a video about it. Either way best of luck with this and looking forward to it, as one thing always intrigues me when other developers approaches this and which methods they eventually use to take on this task.

**Comment by Gmod4phun** [comment]
@RafaelDeJongh First of all, I must say thank you so much for being a part of the CAP team. I have had alot of fun throughout the years :)

With the current state of s&box, there won't be any progress until the entity system is fully replaced with the upcoming scene system - aka shit will break and will need to be recoded anyway. Let's hope it will be for the better. About the kawoosh, I finally got around to making the video.

https://www.youtube.com/watch?v=On76A5eswIU

The kawoosh is created using a model with shape keys to control the extrusion of the kawoosh, and a custom shader. Also I made it use 2 layers - an outer model and an inner, scaled down model with a slightly different material/color to make it look a bit nicer.

It also shows the new Pegasus gate model to go along with the new Milky Way gates (credit goes to David Gian-Cursio for making the amazing high poly versions - https://davidcgc.artstation.com/). The textures are not final, just something thrown together quickly to look okay-ish and I will probably be reworking the low poly models again at some point.

**Pull request merged**
